# labels in use
---
#problems
- name: "bug"
  color: "d8345f"
  description: "Something isn't working"
- name: "security"
  color: "d8345f"
  description: "security, security"
#feedback
- name: "discussion"
  color: "856c8b"
  description: "keep the discussion going"
- name: "question"
  color: "856c8b"
  description: "questions need answers"
#improvements
- name: "enhancement"
  color: "a8d3da"
- name: "optimisation"
  color: "a8d3da"
  description: "improve and implementation"
#products
- name: "cost-management"
  color: "98ddca"
- name: "compliancy"
  color: "98ddca"
- name: "service-management"
  color: "98ddca"
- name: "project-plannin"
  color: "98ddca"
- name: "dexmove"
  color: "98ddca"
- name: "aks"
  color: "98ddca"
- name: "wvd"
  color: "98ddca"
#state
- name: "triage"
  color: "e8e9a1"
  description: "work needs triage"
- name: "commited"
  color: "e8e9a1"
  description: "commited work, but not yet planned"
- name: "planned"
  color: "e8e9a1"
  description: "planned work, but not yet started ;-)"
- name: "in-progress"
  color: "e8e9a1"
  description: "working on it!"
#inactive
- name: "wontfix"
  color: "cdc9c3"
  description: "We will not fix this"
- name: "on-hold"
  color: "cdc9c3"
  description: "waiting for additional input"
- name: "duplicate"
  color: "cdc9c3"
  description: "duplicate work"
- name: "invalid"
  color: "cdc9c3"
  description: "not accepted as valid input"
#addition
- name: "feature"
  color: "a7e9af"
  description: "new functionality"
#experience
- name: "design"
  color: "f0cf85"
- name: "ux"
  color: "f0cf85"