# Issue labeler based on body content

# ## Issue labels
# Bug, Feature and triage labels are added via the template.

# ## Produc labels
#Add 'product:cost management' if issue contains the selection cost management
"cost-management":
  - '\[x\] Cost management'

#Add 'product:compliancy' if issue contans the selection compliancy
"compliancy":
  - '(\[x\] Compliancy)'

#Add 'product:service delivery' if issue contans the selection serviced elivery
"service-management":
  - '(\[x\] Service Delivery)'

#Add 'product:project planning' if issue contans the selection project planning
"project-planning":
  - '(\[x\] Project Planning)'

#Add 'product:wvd' if issue contans the selection wvd
"wvd":
  - '(\[x\] Windows Virtual desktop (WVD))'

#Add 'product:aks' if issue contans the selection aks
"aks":
  - '(\[x\] Azure Kubernetes Service (AKS))'

#Add 'product:aks' if issue contans the selection aks
"dexmove":
  - '(\[x\] DexMove)'