# Issue labeler based on body content

# ## Issue labels
# Bug and Feature labels are added via the template.

# ## Produc labels
#Add 'product:cost management' if issue contains the selection cost management
"[product] cost management":
  - '\[x\] Cost management'

#Add 'product:compliancy' if issue contans the selection compliancy
"[product] compliancy":
  - '(\[x\] Compliancy)'

#Add 'product:service delivery' if issue contans the selection serviced elivery
"[product] service delivery":
  - '(\[x\] Service Delivery)'

#Add 'product:project planning' if issue contans the selection project planning
"[product] project planning":
  - '(\[x\] Project Planning)'

#Add 'product:wvd' if issue contans the selection wvd
"[product] wvd":
  - '(\[x\] Windows Virtual desktop (WVD))'

#Add 'product:aks' if issue contans the selection aks
"[product] aks":
  - '(\[x\] Azure Kubernetes Service (AKS))'

#Add 'product:aks' if issue contans the selection aks
"[product] dexmove":
  - '(\[x\] DexMove)'