name: "Welcome first interactions"

on:
  issues:
    types: [opened]

jobs:
  welcome:
    name: welcome first interactions
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for opening your first issue. A DexMach team member should pop by to give feedback soon.'