name: "Welcome first interactions"
on:
  issues:
    types: [opened]

jobs:
  triage:
    runs-on: ubuntu-latest

steps:
- uses: actions/first-interaction@v1
  with:
    repo-token: ${{ secrets.GITHUB_TOKEN }}
    issue-message: 'Thanks for opening your first issue!'