name: "Auto label Issues"

on:
  issues:
    types: [opened, edited]

jobs:
  labeler:
    name: Auto label issues
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v2.3
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        enable-versioned-regex: 0