name: Add new issue to Triage column in projectboard

on:
  issues:
    types: [opened, reopened]
jobs:
  Add_New_Issue_To_Project:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/actions-add-new-issue-to-column@v1.1
      with:
        action-token: "${{ secrets.ACCESS_TOKEN }}"
        project-url: "https://github.com/stijnc/testconfig/projects/1"
        column-name: "Triage"